server.port=8082
spring.application.name=login

spring.data.mongodb.database=login_db
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017

jwt.secret=Z3VhcmRhbmRvU2VndXJhbmNhQ29tU3ByaW5nQm9vdDIwMjYhQDEyMw
jwt.expiration=3600000